# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gateway_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GatewayTree(object):
    def setupUi(self, GatewayTree):
        GatewayTree.setObjectName("GatewayTree")
        GatewayTree.resize(845, 597)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/ip-phone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GatewayTree.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(GatewayTree)
        self.centralwidget.setObjectName("centralwidget")
        self.tree_gateway = QtWidgets.QTreeWidget(self.centralwidget)
        self.tree_gateway.setGeometry(QtCore.QRect(10, 30, 811, 511))
        self.tree_gateway.setObjectName("tree_gateway")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tree_gateway.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tree_gateway.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tree_gateway.headerItem().setFont(2, font)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tree_gateway.headerItem().setFont(3, font)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tree_gateway.headerItem().setFont(4, font)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tree_gateway.headerItem().setFont(5, font)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tree_gateway.headerItem().setFont(6, font)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        GatewayTree.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GatewayTree)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 21))
        self.menubar.setObjectName("menubar")
        GatewayTree.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GatewayTree)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        GatewayTree.setStatusBar(self.statusbar)

        self.retranslateUi(GatewayTree)
        QtCore.QMetaObject.connectSlotsByName(GatewayTree)

    def retranslateUi(self, GatewayTree):
        _translate = QtCore.QCoreApplication.translate
        GatewayTree.setWindowTitle(_translate("GatewayTree", "Gateways"))
        self.tree_gateway.headerItem().setText(0, _translate("GatewayTree", "Name"))
        self.tree_gateway.headerItem().setText(1, _translate("GatewayTree", "UUID"))
        self.tree_gateway.headerItem().setText(2, _translate("GatewayTree", "Description"))
        self.tree_gateway.headerItem().setText(3, _translate("GatewayTree", "Model"))
        self.tree_gateway.headerItem().setText(4, _translate("GatewayTree", "Units"))
        self.tree_gateway.headerItem().setText(5, _translate("GatewayTree", "SubUnits"))
        self.tree_gateway.headerItem().setText(6, _translate("GatewayTree", "Endpoints"))
        self.label.setText(_translate("GatewayTree", "Gateways"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GatewayTree = QtWidgets.QMainWindow()
    ui = Ui_GatewayTree()
    ui.setupUi(GatewayTree)
    GatewayTree.show()
    sys.exit(app.exec_())
