# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hunt_group_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HuntGroup(object):
    def setupUi(self, HuntGroup):
        HuntGroup.setObjectName("HuntGroup")
        HuntGroup.resize(525, 336)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/ip-phone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HuntGroup.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(HuntGroup)
        self.centralwidget.setObjectName("centralwidget")
        self.tree_hunt_group = QtWidgets.QTreeWidget(self.centralwidget)
        self.tree_hunt_group.setGeometry(QtCore.QRect(10, 30, 471, 251))
        self.tree_hunt_group.setObjectName("tree_hunt_group")
        self.tree_hunt_group.headerItem().setText(0, "1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        HuntGroup.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HuntGroup)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 525, 21))
        self.menubar.setObjectName("menubar")
        HuntGroup.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HuntGroup)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        HuntGroup.setStatusBar(self.statusbar)

        self.retranslateUi(HuntGroup)
        QtCore.QMetaObject.connectSlotsByName(HuntGroup)

    def retranslateUi(self, HuntGroup):
        _translate = QtCore.QCoreApplication.translate
        HuntGroup.setWindowTitle(_translate("HuntGroup", "Hunt Groups"))
        self.label.setText(_translate("HuntGroup", "Hunt Groups"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HuntGroup = QtWidgets.QMainWindow()
    ui = Ui_HuntGroup()
    ui.setupUi(HuntGroup)
    HuntGroup.show()
    sys.exit(app.exec_())
