# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phone_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_phone_details(object):
    def setupUi(self, phone_details):
        phone_details.setObjectName("phone_details")
        phone_details.resize(513, 489)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/ip-phone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        phone_details.setWindowIcon(icon)
        self.export_btn = QtWidgets.QPushButton(phone_details)
        self.export_btn.setGeometry(QtCore.QRect(20, 460, 471, 23))
        self.export_btn.setObjectName("export_btn")
        self.tableWidget = QtWidgets.QTableWidget(phone_details)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 481, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.main_label = QtWidgets.QLabel(phone_details)
        self.main_label.setGeometry(QtCore.QRect(10, 10, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.main_label.setFont(font)
        self.main_label.setObjectName("main_label")
        self.count_label = QtWidgets.QLabel(phone_details)
        self.count_label.setGeometry(QtCore.QRect(440, 10, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.count_label.setFont(font)
        self.count_label.setObjectName("count_label")

        self.retranslateUi(phone_details)
        QtCore.QMetaObject.connectSlotsByName(phone_details)

    def retranslateUi(self, phone_details):
        _translate = QtCore.QCoreApplication.translate
        phone_details.setWindowTitle(_translate("phone_details", "Phone Details"))
        self.export_btn.setText(_translate("phone_details", "Export to File..."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("phone_details", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("phone_details", "Description"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("phone_details", "Model"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("phone_details", "Line(s)"))
        self.main_label.setText(_translate("phone_details", "Phone Details"))
        self.count_label.setText(_translate("phone_details", "count_label"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    phone_details = QtWidgets.QWidget()
    ui = Ui_phone_details()
    ui.setupUi(phone_details)
    phone_details.show()
    sys.exit(app.exec_())
