# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'callhandler_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Call_Handlers(object):
    def setupUi(self, Call_Handlers):
        Call_Handlers.setObjectName("Call_Handlers")
        Call_Handlers.resize(434, 385)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/ip-phone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Call_Handlers.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Call_Handlers)
        self.centralwidget.setObjectName("centralwidget")
        self.call_handler_label = QtWidgets.QLabel(self.centralwidget)
        self.call_handler_label.setGeometry(QtCore.QRect(30, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.call_handler_label.setFont(font)
        self.call_handler_label.setObjectName("call_handler_label")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 40, 391, 291))
        self.tableView.setObjectName("tableView")
        Call_Handlers.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Call_Handlers)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 434, 21))
        self.menubar.setObjectName("menubar")
        Call_Handlers.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Call_Handlers)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        Call_Handlers.setStatusBar(self.statusbar)

        self.retranslateUi(Call_Handlers)
        QtCore.QMetaObject.connectSlotsByName(Call_Handlers)

    def retranslateUi(self, Call_Handlers):
        _translate = QtCore.QCoreApplication.translate
        Call_Handlers.setWindowTitle(_translate("Call_Handlers", "Call Handlers"))
        self.call_handler_label.setText(_translate("Call_Handlers", "Call Handlers"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Call_Handlers = QtWidgets.QMainWindow()
    ui = Ui_Call_Handlers()
    ui.setupUi(Call_Handlers)
    Call_Handlers.show()
    sys.exit(app.exec_())
