# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vm_users_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VoiceMailUsers(object):
    def setupUi(self, VoiceMailUsers):
        VoiceMailUsers.setObjectName("VoiceMailUsers")
        VoiceMailUsers.resize(435, 396)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/ip-phone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VoiceMailUsers.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(VoiceMailUsers)
        self.centralwidget.setObjectName("centralwidget")
        self.call_handler_label = QtWidgets.QLabel(self.centralwidget)
        self.call_handler_label.setGeometry(QtCore.QRect(20, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.call_handler_label.setFont(font)
        self.call_handler_label.setObjectName("call_handler_label")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 40, 391, 311))
        self.tableView.setObjectName("tableView")
        VoiceMailUsers.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VoiceMailUsers)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 435, 21))
        self.menubar.setObjectName("menubar")
        VoiceMailUsers.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VoiceMailUsers)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        VoiceMailUsers.setStatusBar(self.statusbar)

        self.retranslateUi(VoiceMailUsers)
        QtCore.QMetaObject.connectSlotsByName(VoiceMailUsers)

    def retranslateUi(self, VoiceMailUsers):
        _translate = QtCore.QCoreApplication.translate
        VoiceMailUsers.setWindowTitle(_translate("VoiceMailUsers", "Voicemail Users"))
        self.call_handler_label.setText(_translate("VoiceMailUsers", "Voicemail Users"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VoiceMailUsers = QtWidgets.QMainWindow()
    ui = Ui_VoiceMailUsers()
    ui.setupUi(VoiceMailUsers)
    VoiceMailUsers.show()
    sys.exit(app.exec_())
